name: test action
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: auto semver
        uses: ./
        with:
          major_labels: feature major
          minor_labels: bugfix minor
          patch_labels: hotfix patch
