name: test action
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: auto semver
        uses: ./
        with:
          major_labels: feature,major
          minor_labels: bugFix,minor
          patch_labels: hotfix,patch
